

return {
	{
		name = "Piano",
		instruments = {
			{
				name = "yamaha-grand-piano",
				notes = {
					{ name="A0", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-0.ogg" },
					{ name="A#0", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-sharp-0.ogg" },
					{ name="B0", filename = "__musical-speaker__/sound/yamaha-grand-piano/b-0.ogg" },
					{ name="C1", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-1.ogg" },
					{ name="C#1", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-sharp-1.ogg" },
					{ name="D1", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-1.ogg" },
					{ name="D#1", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-sharp-1.ogg" },
					{ name="E1", filename = "__musical-speaker__/sound/yamaha-grand-piano/e-1.ogg" },
					{ name="F1", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-1.ogg" },
					{ name="F#1", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-sharp-1.ogg" },
					{ name="G1", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-1.ogg" },
					{ name="G#1", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-sharp-1.ogg" },
					{ name="A1", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-1.ogg" },
					{ name="A#1", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-sharp-1.ogg" },
					{ name="B1", filename = "__musical-speaker__/sound/yamaha-grand-piano/b-1.ogg" },
					{ name="C2", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-2.ogg" },
					{ name="C#2", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-sharp-2.ogg" },
					{ name="D2", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-2.ogg" },
					{ name="D#2", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-sharp-2.ogg" },
					{ name="E2", filename = "__musical-speaker__/sound/yamaha-grand-piano/e-2.ogg" },
					{ name="F2", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-2.ogg" },
					{ name="F#2", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-sharp-2.ogg" },
					{ name="G2", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-2.ogg" },
					{ name="G#2", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-sharp-2.ogg" },
					{ name="A2", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-2.ogg" },
					{ name="A#2", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-sharp-2.ogg" },
					{ name="B2", filename = "__musical-speaker__/sound/yamaha-grand-piano/b-2.ogg" },
					{ name="C3", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-3.ogg" },
					{ name="C#3", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-sharp-3.ogg" },
					{ name="D3", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-3.ogg" },
					{ name="D#3", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-sharp-3.ogg" },
					{ name="E3", filename = "__musical-speaker__/sound/yamaha-grand-piano/e-3.ogg" },
					{ name="F3", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-3.ogg" },
					{ name="F#3", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-sharp-3.ogg" },
					{ name="G3", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-3.ogg" },
					{ name="G#3", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-sharp-3.ogg" },
					{ name="A3", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-3.ogg" },
					{ name="A#3", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-sharp-3.ogg" },
					{ name="B3", filename = "__musical-speaker__/sound/yamaha-grand-piano/b-3.ogg" },
					{ name="C4", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-4.ogg" },
					{ name="C#4", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-sharp-4.ogg" },
					{ name="D4", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-4.ogg" },
					{ name="D#4", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-sharp-4.ogg" },
					{ name="E4", filename = "__musical-speaker__/sound/yamaha-grand-piano/e-4.ogg" },
					{ name="F4", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-4.ogg" },
					{ name="F#4", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-sharp-4.ogg" },
					{ name="G4", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-4.ogg" },
					{ name="G#4", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-sharp-4.ogg" },
					{ name="A4", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-4.ogg" },
					{ name="A#4", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-sharp-4.ogg" },
					{ name="B4", filename = "__musical-speaker__/sound/yamaha-grand-piano/b-4.ogg" },
					{ name="C5", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-5.ogg" },
					{ name="C#5", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-sharp-5.ogg" },
					{ name="D5", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-5.ogg" },
					{ name="D#5", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-sharp-5.ogg" },
					{ name="E5", filename = "__musical-speaker__/sound/yamaha-grand-piano/e-5.ogg" },
					{ name="F5", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-5.ogg" },
					{ name="F#5", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-sharp-5.ogg" },
					{ name="G5", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-5.ogg" },
					{ name="G#5", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-sharp-5.ogg" },
					{ name="A5", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-5.ogg" },
					{ name="A#5", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-sharp-5.ogg" },
					{ name="B5", filename = "__musical-speaker__/sound/yamaha-grand-piano/b-5.ogg" },
					{ name="C6", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-6.ogg" },
					{ name="C#6", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-sharp-6.ogg" },
					{ name="D6", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-6.ogg" },
					{ name="D#6", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-sharp-6.ogg" },
					{ name="E6", filename = "__musical-speaker__/sound/yamaha-grand-piano/e-6.ogg" },
					{ name="F6", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-6.ogg" },
					{ name="F#6", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-sharp-6.ogg" },
					{ name="G6", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-6.ogg" },
					{ name="G#6", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-sharp-6.ogg" },
					{ name="A6", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-6.ogg" },
					{ name="A#6", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-sharp-6.ogg" },
					{ name="B6", filename = "__musical-speaker__/sound/yamaha-grand-piano/b-6.ogg" },
					{ name="C7", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-7.ogg" },
					{ name="C#7", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-sharp-7.ogg" },
					{ name="D7", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-7.ogg" },
					{ name="D#7", filename = "__musical-speaker__/sound/yamaha-grand-piano/d-sharp-7.ogg" },
					{ name="E7", filename = "__musical-speaker__/sound/yamaha-grand-piano/e-7.ogg" },
					{ name="F7", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-7.ogg" },
					{ name="F#7", filename = "__musical-speaker__/sound/yamaha-grand-piano/f-sharp-7.ogg" },
					{ name="G7", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-7.ogg" },
					{ name="G#7", filename = "__musical-speaker__/sound/yamaha-grand-piano/g-sharp-7.ogg" },
					{ name="A7", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-7.ogg" },
					{ name="A#7", filename = "__musical-speaker__/sound/yamaha-grand-piano/a-sharp-7.ogg" },
					{ name="B7", filename = "__musical-speaker__/sound/yamaha-grand-piano/b-7.ogg" },
					{ name="C8", filename = "__musical-speaker__/sound/yamaha-grand-piano/c-8.ogg" },
				}
			},
		}
	}
}
